name: Slå ihop kalendrar (ICS → combined.ics)

on:
  schedule:
    - cron: "*/30 * * * *"   # kör var 30:e minut
  workflow_dispatch:

jobs:
  merge:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Merge ICS feeds
        env:
          ICS_URLS: ${{ secrets.ICS_URLS }}       # 4 st URL:er, en per rad
          CAL_LABELS: ${{ secrets.CAL_LABELS }}   # 4 st labels, en per rad (Harald, Familj, Helena, Viggo Aktiviteter)
          MERGE_NAME: ${{ secrets.MERGE_NAME }}   # valfritt (annars default i scriptet)
          OUT_ICS: combined.ics
        run: python merge_ics.py

      - name: Commit if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          if [ -n "$(git status --porcelain combined.ics)" ]; then
            git add combined.ics
            git commit -m "Update combined.ics"
            git push
          else
            echo "No changes."
          fi
